### PR TITLE
Fixed some issues with terra and ignis imbued fire

### PR DESCRIPTION
**Pull request by Timeslice42**

### CODE REVIEW

**Comment by nekosune** [comment]
Hey canya squash the commits then will commit, sorry for the huge delay, I have been busy moving, and trouble related

**Comment by Timeslice42** [comment]
How would I do that, and why would you need me to?

**Comment by nekosune** [comment]
https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

It makes things tidier for one thing and easier to keep organised

**Comment by Timeslice42** [comment]
That's what I got after squashing, but that looks like more history, not less...

**Comment by nekosune** [comment]
looks like something is mixed up :S

**Comment by Timeslice42** [comment]
Any advice? We're into territory in github that I've not tread before.

**Comment by Timeslice42** [comment]
If I roll back the merge it looks like we want it to, but I can't commit that, it just thinks my branch is out of date.

**Comment by nekosune** [comment]
ok to test

**Comment by nekosune** [comment]
((sorry testing something, also :) I think you can force push))

**Comment by Timeslice42** [comment]
So, has this been merged? Can I close the PR?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
