### PR TITLE
Fixed a minor typo

### PR DESCRIPTION
**Pull request by Sunconure11**
If this is the right branch, anyways.

### CODE REVIEW

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by Sunconure11** [comment]
Maybe you should have one of them verify it now, it just fixes a weird typo that has been in the Water Imbued potion effect for quite some time.

**Comment by nekosune** [comment]
test this now

**Comment by nekosune** [comment]
and sorry, it's a minor bug in jenkins need to figure out

**Comment by nekosune** [comment]
test this please

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Okay, I REALLY need to fix jenkins, in the mean time

**Pull request merged**
