### PR TITLE
Fix enderchest dupe bug

### LINKED ISSUE #659: Dupe bug with enderchests
If you pick up block with the dislocation focus, then try to place it against enderchest's lock (the one you can use diamond on), you get kicked out of the server. When you log back in, there's one block in front of the enderchest and another one in focus.

ThaumicTinkerer-2.5-1.7.10-440
EnderStorage-1.7.10-1.4.5.27
Forge 1236 (the lastest for cauldron)

The same happens with singleplayer, but the client crashes with this
https://gist.github.com/Meegooo/7e3bd9dab3bc13e43a05

### PR DESCRIPTION
**Pull request by Meegooo**
Fixes #659

### CODE REVIEW

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
ok to test

**Comment by Meegooo** [comment]
Basically, what it used to do when placing a block
1. Save block you clicked at (line 82).
2. Change coordinates where block should be placed (lines 89 to 101).
3. Set block on coordinates from paragraph 2 (line 105)
4. Call .onBlockPlacedBy (line 106) for block in paragraph 1, but pass wrong coordinates from paragraph 2.

Since you don't place block you clicked at, you place block from wand, .onBlockPlacedBy should be called for block in wand

PS. I don't know why, but there're a lot of places, where code tries to access private fields. For example *thaumic.tinkerer.common.item.kami.armor.ItemGemHelm* in lines 74, 75, 87, 88; or  *thaumic.tinkerer.common.item.kami.ItemCatAmulet* in lines 70, 71, 78, 79, 107. 
And even in dev version from jenkins it's broken. When I changed slot in inventory, i crashed with this https://gist.github.com/Meegooo/7adfcdf3869ab4c75619

**Comment by Meegooo** [comment]
And yes, for me it looks like line 106 is broken as well.
Shouldn't you pass coordinates of block you're looking at? Because now it passes coordinates of a new block

**Comment by nekosune** [comment]
I wonder if it is ignoring the AT now, will check that. By the way the ok to test thing was just to tell jenkins to do a test compile of your PR.

**Comment by nekosune** [comment]
.... Jenkins stop being dumb, It does not need compiling a second time

**Comment by nekosune** [comment]
https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/blob/develop/src/main/resources/ThaumicTinkerer_at.cfg#L17
We have an AT in use, it looks like for some reason your dev env is not reading it, it works fine in mine

**Comment by Meegooo** [comment]
Eh, maybe.
I just cloned the repo, IDEA resolved gradle dependencies and that's about it.
But shouldn't it work for dev jar file?

**Comment by nekosune** [comment]
depends how it is being run really. Will check on things though

**Comment by Meegooo** [comment]
BTW, I want to add BlockBreak and BlockPlace events for dislocation focus. It's done, but both commits change the same line.
I can create new PR, but this PR has to be merged. Or I can just add new commit to this PR.

**Comment by nekosune** [comment]
We will NOT be adding those events
They are not suited for a block that moves, as some mods use break to clear up things and remove information a block had stored

**Comment by Meegooo** [comment]
hm, okay then

**Comment by nekosune** [comment]
As several mods move blocks, I am thinking of pulling part out into a library, and letting that library contain a new event, mostly for the block protection plugins/mods, that would let it cancel the events happening. I dont know if i would get much use from others of the library, but at the moment, people mostly assume BlockBreak = removed from the world fully

**Comment by Meegooo** [comment]
Hm, yea.
Only if PlayerInteractionEvent worked as it should. But for some reason this event fires 2 times if you RMB on a block.

**Pull request merged**
