### PR TITLE
Fixed some research never completing (and a small thing with Telekenesis research)

### PR DESCRIPTION
**Pull request by TheCodex6824**
I did ~~2~~ 3 things here:

- I removed the AUTOUNLOCK property from the research that had it, which makes it properly complete now (the research that didn't have it was working already)
- I changed some stuff in the Telekenesis research because it conflicted with the Vis Battery research
- **(Edit 5/1)** I fixed some multiblock stuff that referenced a client class and crashed dedicated servers

### CODE REVIEW

**Comment by Frikkle** [comment]
Any news on this PR or any way we can help getting it tested/merged?

**Comment by TheCodex6824** [comment]
I just fixed a crash on dedicated servers I ran into while testing this fix again, if anyone else can verify that it works for them as well that would be great.

**Comment by geisterfurz007** [comment]
Just for documenting: Related issue is #937

**Comment by nekosune** [comment]
Pulled code in with attribution,

**Pull request closed without merging**
