### PR TITLE
Kill language handler

### LINKED ISSUE #448: Vanilla localization handling/auto detect .lang files
Since 1.6.x FML auto-detect .lang files. So entries in LibResources.java no longer needed. Also, LanguageRegistry.java in FML marked as Deprecated and will be removed in 1.8. https://github.com/MinecraftForge/FML/blob/master/src/main/java/cpw/mods/fml/common/registry/LanguageRegistry.java

### PR DESCRIPTION
**Pull request by Adaptivity**
Closes #448 Based on this commit: https://github.com/Vazkii/Botania/commit/652ac3f3acccd9c0c252f7c2e967103fef2c03e7

### CODE REVIEW

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Hey, next time, please actually test before pring? dosnt compile

**Comment by Adaptivity** [comment]
Sorry. I'll be carefully next time.

**Pull request merged**
