### PR TITLE
Ichor pick blockupdate fixes

### PR DESCRIPTION
**Pull request by Midnight145**
ToolHander.java now sends block updates in all cases, and ItemIchorPickAdv.java now handles an edge case where you can be standing just far enough away to break the 4.5 block raytrace check [here](https://github.com/Midnight145/ThaumicTinkerer/blob/f56f5a58bb6cb1689e492929e76f45c56495bd60/src/main/java/thaumic/tinkerer/common/item/kami/tool/ToolHandler.java#L75)

Sorry about the earlier pull request, I accidentally both built on and chose the wrong branches.

### CODE REVIEW

**Comment by Midnight145** [comment]
not sure why it's trying to pull my amulet commits again, lmk if there's no way to just cherry pick the ichor pick commit and I can make sure that I didn't break anything on my end, which is likely what happened

**Comment by Dream-Master** [comment]
not sure if Thaumic Thinker main repo just make new 1.7.10 releases but we did. https://github.com/GTNewHorizons/ThaumicTinkerer

**Comment by KatrinaAS** [comment]
Must admit it is hard to see the changes made with the reformatting done. which has also added conflicts to the cleaning talismen

**Comment by KatrinaAS** [comment]
Ok I must admit, I do not like how the conflict fix adds a commit from me onto your repo, that feels like a security flaw

**Comment by Midnight145** [comment]
Yeah, I don't think my original branch was up-to-date after the talisman pull request was merged, so it tried to re-pull my talisman commits. Sorry about that, I'll make sure I don't do that next time.

**Pull request merged**
