### PR TITLE
fix the slab recipe

### PR DESCRIPTION
**Pull request by Dream-Master**
I fix the slab recipe and give it a name in the lang file.

### CODE REVIEW

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by Dream-Master** [comment]
It works

image

**Comment by nekosune** [comment]
Now try how well the slabs actually work. which is the main problem.

**Comment by Dream-Master** [comment]
Ok i make spelling errors and the slab not realy work only as double slabs.

**Comment by nekosune** [comment]
The slabs dont have a recipe, because they do not work yet. They are unfinished

**Pull request closed without merging**
