### PR TITLE
Fixed ShadowBeam particle:

### PR DESCRIPTION
**Pull request by DrQwertySilence**
Now uses thaumcraft particle engine.
Rewrite of inner class "Particle" in "ItemFocusShadowbeam" class.
Little rewrite to inner class "Beam" in "ItemFocusShadowbeam" class to make it more configurable.

### CODE REVIEW

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by nekosune** [comment]
Can one of the admins verify this patch?

**Comment by DrQwertySilence** [comment]
Now with less "shit".

**Comment by nekosune** [comment]
Thankyou VERY much :)

**Pull request merged**
